blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestEntriesFeed
from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from .models import Post, Category


app_name = 'blog'

infodict_posts = {
    'queryset': Post.find(),
    'date_field': 'published_date',
    'priority': 0.9,
    'changefreq': 'weekly'
}
infodicts_categories = {
    'queryset': Category.objects.order_by('name'),
    'date_field': None,
    'priority': 0.5,
    'changefreq': 'monthly'
}


class StaticSitemap(Sitemap):
    changefreq = 'weekly'
    priority = '0.8'

    def items(self):
        return ['/']

    def location(self, item):
        return item


sitemaps = {
    'static': StaticSitemap,

    'artigos': GenericSitemap(
        infodict_posts,
        priority=0.7, changefreq='weekly'
    ),

    'categories': GenericSitemap(
        infodicts_categories,
        priority=0.5, changefreq='monthly')
}

urlpatterns = [
    path('', views.index, name='index'),
    path('artigos/', views.post_list, name='artigos'),
    path('artigo/<category>/<slug>/<pk>', views.post_details, name='artigo'),
    path('artigos/tag/<tag_name>', views.tag, name='post_by_tag'),
    path(
        'categoria/<category_slug>',
        views.post_by_category,
        name='post_by_cat'
    ),
    path('busca/', views.search, name='search'),
    path('contato/', views.contato, name='contato'),
    path('feed/', LatestEntriesFeed()),
    path('sitemap.xml', sitemap, {
        'sitemaps': sitemaps,
    }),
    path(
        'sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps},
        name='sitemaps'
    )
]

fazendoissoerrado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django_comments.feeds import LatestCommentFeed


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sumernote/', include('django_summernote.urls')),
    path('', include('blog.urls')),
    path('comments/', include('django_comments.urls')),
    path('comments/feed/', LatestCommentFeed()),

]
# if settings.DEBUG:
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns += staticfiles_urlpatterns()

blog/models.py
import os
import glob
from slugify import slugify
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.utils import timezone
from taggit.managers import TaggableManager
# Create your models here.


class Category(models.Model):
    name = models.CharField('Nome', max_length=255)
    slug = models.CharField('Slug', max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/categoria/{}".format(self.slug)

    def save(self):
        self.slug = slugify(self.name)
        super(Category, self).save()


class Post(models.Model):
    title = models.CharField('Título', max_length=255)
    subtitle = models.CharField(max_length=255, blank=True, null=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT
    )
    slug = models.CharField(max_length=255, null=True, blank=True)
    content = models.TextField('Conteúdo', blank=True, null=True)
    meta_description = models.TextField('meta-description')
    cover = models.ImageField(
        'Capa', upload_to='post/cover/', blank=True, null=True
    )
    published = models.BooleanField('Publicado', default=False)
    created_date = models.DateTimeField('Criado em', default=timezone.now)
    published_date = models.DateTimeField(
        'Publicado em',
        blank=True,
        null=True
    )
    views = models.IntegerField(default=0, null=True, blank=True)
    tags = TaggableManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/artigo/{}/{}/{}".format(
            self.category.slug, self.slug, self.pk
        )

    def increment_view_count(self):
        post = Post.objects.filter(pk=self.pk)
        post.views += 1
        post.save()

    @classmethod
    def find(cls):
        try:
            return cls.objects.filter(
                published_date__lte=timezone.now()
            ).filter(published=True).order_by('-published_date').all()
        except Exception:
            return None

    @classmethod
    def taglist(cls):
        return cls.tags.all()

    def save(self):
        self.slug = slugify(self.title)
        if self.pk:
            this = Post.objects.get(pk=self.pk)
            try:
                if this.cover != self.cover:
                    path = "%s*" % (this.cover.path)
                    for arq in glob.glob(path):
                        os.remove(arq)
            except Exception:
                pass

        super(Post, self).save()


@receiver(pre_delete, sender=Post)
def delete_cover(sender, instance, *args, **kwargs):
    if instance.cover:
        if os.path.isfile(instance.cover.path):
            os.remove(instance.cover.path)

blog/forms.py
# coding: utf-8
from django import forms


class ContatoForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ContatoForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            placeholder = '{}'
            if visible.field.required:
                placeholder = '{} *'
            visible.field.widget.attrs['placeholder'] = placeholder.format(
                visible.name.title()
            )

    nome = forms.CharField(required=True)
    email = forms.CharField(required=True)
    telefone = forms.CharField(required=False)
    mensagem = forms.CharField(widget=forms.Textarea, required=True)

blog/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .models import Post
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.db.models import Q
from .forms import ContatoForm
import smtplib
from django.contrib import messages
from django.core.mail import BadHeaderError
# from django.views.decorators.cache import cache_page
from fazendoissoerrado.settings import (
    CONTACT_EMAIL_BOX,
    EMAIL_HOST,
    EMAIL_PORT,
    EMAIL_HOST_USER,
    EMAIL_HOST_PASSWORD,
    EMAIL_USE_SSL,
    # CACHE_TTL
)


# Create your views here.
# cache_ttl = int(CACHE_TTL)


# @cache_page(cache_ttl)
def post_details(request, category, slug, pk):
    queryset = Post.objects.filter(
        published=True
    ).filter(
        published_date__lt=timezone.now()
    ).filter(pk=pk)
    post = get_object_or_404(queryset)
    keywords = post.taglist()
    ''' prevent counter view to repeat counter on update page '''
    last_post = request.session.get('LAST_POST', None)
    this_post = request.path
    if not last_post or this_post != last_post:
        ''' increment counter from post '''
        post.views += 1
        post.save()
        ''' remember the last post viewed '''
        request.session['LAST_POST'] = this_post

    return render(
        request,
        'blog/post_details.html',
        {'post': post, 'keywords': keywords}
    )


# @cache_page(cache_ttl)
def post_list(request):
    page = request.GET.get('page', 1)
    post_search = Post.find()
    paginator = Paginator(post_search, 10)
    posts = paginator.get_page(page)

    return render(
        request,
        'blog/post_list.html',
        {'posts': posts}
    )


# @cache_page(cache_ttl)
def post_by_category(request, category_slug):
    page = request.GET.get('page', 1)
    post_search = Post.objects.filter(
        published_date__lte=timezone.now()
    ).filter(
        published=True
    ).filter(
        category__slug=category_slug
    ).order_by('-published_date').all()

    paginator = Paginator(post_search, 10)
    posts = paginator.get_page(page)

    return render(
        request,
        'blog/post_list.html',
        {'posts': posts}
    )


# @cache_page(cache_ttl)
def index(request):
    page = 1
    highlights = Post.find()[:3]
    post_search = Post.find()
    paginator = Paginator(post_search, 10)
    pagination = paginator.get_page(page)
    posts = pagination[3:]

    return render(
        request,
        'blog/index.html',
        {
            'posts': posts,
            'highlights': highlights,
            'pagination': pagination
        }
    )


def search(request):
    page = request.GET.get('page', 1)
    q = request.GET.get('q', None)
    if q:
        post_search = Post.objects.filter(
            published_date__lte=timezone.now()
        ).filter(published=True).filter(
            Q(title__icontains=q) |
            Q(subtitle__icontains=q) |
            Q(content__icontains=q)
        ).order_by('-published_date').all()

        paginator = Paginator(post_search, 10)
        posts = paginator.get_page(page)

        return render(
            request,
            'blog/search.html',
            {'posts': posts, 'q': q}
        )

    return redirect('/')


# @cache_page(cache_ttl)
def tag(request, tag_name):
    page = request.GET.get('page', 1)
    post_search = Post.objects.filter(
        published_date__lte=timezone.now()
    ).filter(published=True).filter(
        tags__name__in=[tag_name]
    ).order_by('-published_date').all()

    if not post_search:
        return render(
            request,
            'blog/list_by_tag.html'
        )

    paginator = Paginator(post_search, 10)
    posts = paginator.get_page(page)

    return render(
        request,
        'blog/list_by_tag.html',
        {'posts': posts}
    )


# @cache_page(cache_ttl)
def contato(request):
    assunto = 'Fazendo Isso Errado - Contato do Site'
    form = ContatoForm()
    if request.method == 'POST':
        if form.is_valid():
            nome = form.cleaned_data['nome']
            email = form.cleaned_data['email']
            telefone = form.cleaned_data['telefone']
            msg = form.cleaned_data['mensagem']

            body_message = u"Nome: {}\nEmail: {}\nTelefone: {}\n\n{}".format(
                nome, email, telefone, msg
            )

            mensagem = u"\r\n".join((
                "From: %s" % EMAIL_HOST_USER,
                "To: %s" % CONTACT_EMAIL_BOX,
                "Subject: %s" % assunto,
                "Reply-To: %s" % email,
                "",
                body_message
            )).encode('utf-8')

            try:
                if EMAIL_USE_SSL is True:
                    smtp = smtplib.SMTP_SSL(EMAIL_HOST, EMAIL_PORT)
                    smtp.login(EMAIL_HOST_USER, EMAIL_HOST_PASSWORD)
                else:
                    smtp = smtplib.SMTP(EMAIL_HOST, EMAIL_PORT)
                    smtp.use_ehlo_or_helo_if_needed()

                smtp.sendmail(EMAIL_HOST_USER, [CONTACT_EMAIL_BOX], mensagem)
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    "E-mail enviado com sucesso!"
                )
                smtp.quit()
            except BadHeaderError:
                messages.add_message(
                    request,
                    messages.ERROR,
                    "Houve um erro ao enviar a mensagem (Bad Header)"
                )
            except Exception as e:
                messages.add_message(
                    request,
                    messages.ERROR,
                    "Houve um erro ao enviar a mensagem"
                )
                print(e)

    return render(request, 'blog/contato.html', {'form': form})

blog/templates/blog/contato.html
{% extends "blog/default.html" %}
{% load static %}
{% block site_title %}Contato{% endblock %}
{% block og_type %}website{% endblock %}
{% block og_title %}Contato{% endblock %}
{% block meta_keywords %}contato, fale conosco, redes sociais,{% endblock %}
{% block meta_description %} Fazendo Isso Errado | Contato do site {% endblock %}

{% block content %}
<section id="contact">
	<div class="contact">
  		<div class="container">
       		<h2 class="text-center">CONTATO</h2>
   			<div class="row">
    			<div class="col-sm-12 padding_all">
	  				<div class="col-sm-6 padding_all">
	   					<div class="contact_4">
	    					<h4>ENVIE SUA MENSAGEM</h4>
							<p>Você será respondido o mais breve possível</p>
	   					</div>
						<form method="post" enctype="multipart/form-data" id="cf">
							{% csrf_token %}
	  						<div class="col-sm-12 drop_2 clearfix">
	   							<div class="col-sm-4 drop_2">
	    							<div class="contact_5">
										{{ form.nome }}
									</div>
	   							</div>
	   							<div class="col-sm-4 drop_2">
	    							<div class="contact_5">
										{{ form.email }}
									</div>
	   							</div>
	   							<div class="col-sm-4 drop_2">
							    	<div class="contact_5">
										{{ form.telefone }}
									</div>
								</div>
							</div>
	  						<div class="col-sm-12 drop_2">
	   							<div class="contact_6">
									{{ form.mensagem }}
								</div>
								<div class="contact_7">
	     							<ul>
										<li><button type="submit">ENVIAR</button></li>
										<li><button type="reset">LIMPAR</button></li>
		 							</ul>
	   							</div>
	  						</div>
						</form>
	 				</div>
	 				<div class="col-sm-6 padding_all">
						<div class="contact_4">
	    					<h4>ACOMPANHE NOSSAS REDES SOCIAIS</h4>
							<p>Twitter <a href="#">@fazendoissoerrado</a></p>
							<p>Instagram <a href="#">@fazendoissoerrado</a></p>
	   					</div>
	 				</div>
				</div>
   			</div>
  		</div>
	</div>
</section>
{% endblock %}
{% block sidebar %} {% endblock %}
{% block css_script %}
<style>
button[type="submit"], button[type="reset"]{
	border:none;
	background-color: transparent;
	font-weight: 700;
	font-size: 18px;
	letter-spacing: 3px;
}
</style>
{% endblock %}
{% block js_script %}
<script type="text/javascript" src="{% static 'js/jquery.mask.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('input[name=telefone]').mask('(00)0000-00009');
});
</script>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/default.html" %}
{% load static %}
{% load imagekit %}
{% load comments %}
{% block site_title %}Inicio{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12 padding_all">
   <div class="col-sm-8">
     <div class="center_1">
       <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
        	<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        	<li data-target="#carousel-example-generic" data-slide-to="1" class=""></li>
        	<li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
         {% for high in highlights %}
		 <div class="item {% if forloop.counter == 1 %}active{% endif %}" onclick="location.href='{{ high.get_absolute_url }}'" >
			{% if high.cover %}
	           	{% thumbnail '800x468' high.cover -- alt="..." %}
			{% endif %}
			<div class="carousel-caption" onclick="location.href='{{ high.get_absolute_url }}'">
				<h2><a href="{{ high.get_absolute_url }}">{{ high.title|truncatewords:16 }}</a></h2>
          	</div>
        </div>
        {% endfor %}
      </div>
      <!-- Controls -->
      <a class="left carousel-control" href="http://bootsnipp-env.elasticbeanstalk.com/iframe/xBdN#carousel-example-generic" data-slide="prev">
       <span class="glyphicon glyphicon-chevron-left"></span>
     </a>
     <a class="right carousel-control" href="http://bootsnipp-env.elasticbeanstalk.com/iframe/xBdN#carousel-example-generic" data-slide="next">
       <span class="glyphicon glyphicon-chevron-right"></span>
     </a>
   </div>
 </div>
 {% for post in posts %}
 <div class="col-sm-12 padding_all">
  <div class="center_4 clearfix">
   <div class="col-sm-4">
     <div class="center_2">
       {% if post.cover %}
       <a href="{{ post.get_absolute_url }}">{% thumbnail '260x170' post.cover -- width='100%' %}</a>
       {% endif %}
     </div>
   </div>
   <div class="col-sm-8">
    <div class="center_3">
     <h6><a href="{{ post.get_absolute_url }}">{{ post.author.first_name|upper }}</a>,
     {{ post.published_date|date:"d \d\e F \d\e Y H:i" }}</h6>
     <h3><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a></h3>
     <p>{{ post.content|striptags|truncatewords:36 }}</p>
     <ul>
	  <li class="well_5"><a href="{{ post.category.get_absolute_url }}">{{ post.category.name }}</a></li>
      {% for tag in post.tags.all %}
      <li class="well_5"><a href="/artigos/tag/{{ tag.name }}">{{ tag.name }}</a></li>
      {% endfor %}
	  <li>{{ post.views }} <i class="fa fa-eye"></i></li>
      {% get_comment_count for post as comment_count %}
      <li><a href="#comments">{{ comment_count }} <i class="fa fa-comment"></i></a> </li>

    </ul>
  </div>
</div>
</div>
</div>
{% endfor %}
<div class="center_5 clearfix">
  <ul>
   {% if pagination.has_previous %}
   <li><a href="/artigos?page=1">&laquo</a></li>
   <li><a href="/artigos?page={{ pagination.previous_page_number }}">&lt;</a></li>
   {% endif %}

   <li class="well_6">{{ pagination.number }}</li>

   {% if pagination.has_next %}
   <li><a href="/artigos?page={{ pagination.next_page_number }}">&gt;</a></li>
   <li><a href="/artigos?page={{ pagination.paginator.num_pages }}">&raquo;</a></li>
   {% endif %}
 </ul>
</div>
</div>
{% endblock %}

blog/templates/blog/list_by_tag.html
{% extends "blog/default.html" %}
{% load static %}
{% load imagekit %}
{% load comments %}
{% block site_title %}Inicio{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12 padding_all">
		<div class="col-sm-8">
			{% if not posts %}
			<h3>Nenhum resultado encontrado</h3>
			{% endif %}
			{% for post in posts %}
			<div class="col-sm-12 padding_all">
				<div class="center_4 clearfix">
					<div class="col-sm-4">
						<div class="center_2">
							{% if post.cover %}
							<a href="{{ post.get_absolute_url }}">{% thumbnail '260x170' post.cover -- width='100%' %}</a>
							{% endif %}
						</div>
					</div>
					<div class="col-sm-8">
						<div class="center_3">
							<h6><a href="{{ post.get_absolute_url }}">{{ post.author.first_name|upper }}</a>,
							{{ post.published_date|date:"j F Y H:i" }}</h6>
							<h3><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a></h3>
							<p>{{ post.content|striptags|truncatewords:36 }}</p>
							<ul>
								<li class="well_5"><a href="{{ post.category.get_absolute_url }}">{{ post.category.name }}</a></li>
								{% for tag in post.tags.all %}
								<li class="well_5"><a href="/artigos/tag/{{ tag.name }}">{{ tag.name }}</a></li>
								{% endfor %}
								<li>{{ post.views }} <i class="fa fa-eye"></i></li>
								{% get_comment_count for post as comment_count %}
								<li><a href="#comments">{{ comment_count }} <i class="fa fa-comment"></i></a> </li>

							</ul>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
			{% if posts %}
			<div class="center_5 clearfix">
				<ul>
					{% if posts.has_previous %}
					<li><a href="?page=1">&laquo</a></li>
					<li><a href="?page={{ posts.previous_page_number }}">&lt;</a></li>
					{% endif %}

					<li class="well_6">{{ posts.number }}</li>

					{% if posts.has_next %}
					<li><a href="?page={{ posts.next_page_number }}">&gt;</a></li>
					<li><a href="?page={{ posts.paginator.num_pages }}">&raquo;</a></li>
					{% endif %}
				</ul>
			</div>
			{% endif %}
		</div>
		{% endblock %}

blog/templates/blog/post_details.html
{% extends "blog/default.html" %}
{% load static %}
{% load imagekit %}
{% load comments %}
{% block site_title %}{{ post.title }}{% endblock %}
{% block og_type %}article{% endblock %}
{% block og_title %}{{ post.title }}{% endblock %}
{% block og_description %}{{ post.meta_description }}{% endblock %}
{% block og_image %}/media/{{ post.cover }}{% endblock %}
{% block meta_keywords %} {{ keywords|join:", " }}, {% endblock %}
{% block meta_description %}{{ post.meta_description }}{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-12 padding_all">
		<div class="col-sm-8">
			<div class="blog_1">
				<ul>
					{% for tag in post.tags.all %}
					<li><a href="/artigos/tag/{{ tag.name }}">{{ tag.name }}</a></li>
					{% endfor %}
				</ul>
				<h2>{{ post.title }}</h2>
			</div>
			<div class="col-sm-12 padding_all">
				<div class="col-sm-10 padding_all">
					<div class="blog_2">
						<h4><a href="#">{{ post.author.first_name|upper }}</a>, {{ post.published_date|date:"j F Y H:i" }} </h4>
					</div>
				</div>
				<div class="col-sm-2 padding_all">
					<div class="blog_3">
						<ul>
							<li>{{ post.views }} <i class="fa fa-eye"></i></li>
							{% get_comment_count for post as comment_count %}
							<li>{{ comment_count }} <i class="fa fa-comment"></i></li>
						</ul>
					</div>
				</div>
			</div>
		<div class="col-sm-12 padding_all">
			<div class="blog_11">
				<p><a href="#">
				{% thumbnail '750x412' post.cover -- width='100%' %}
				</a></p>
			</div>
		</div>
		<div class="col-sm-12 padding_all">
				<div class="blog_5">
	    			<!-- AddToAny BEGIN -->
					<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
						<a class="a2a_dd" href="https://www.addtoany.com/share"></a>
						<a class="a2a_button_facebook"></a>
						<a class="a2a_button_twitter"></a>
						<a class="a2a_button_email"></a>
						<a class="a2a_button_whatsapp"></a>
						<a class="a2a_button_reddit"></a>
						<a class="a2a_button_telegram"></a>
						<a class="a2a_button_tumblr"></a>
						<a class="a2a_button_blogger"></a>
						<a class="a2a_button_facebook_messenger"></a>
						<a class="a2a_button_digg"></a>
						<a class="a2a_button_vk"></a>
						<a class="a2a_button_wordpress"></a>
					</div>
					<script>
					var a2a_config = a2a_config || {};
					a2a_config.locale = "pt-BR";
					</script>
					<script async src="https://static.addtoany.com/menu/page.js"></script>
					<!-- AddToAny END -->
			</div>
		</div>


	<div class="col-sm-12 padding_all">
		<div class="details_1">
			{% autoescape off %}
			{{ post.content }}
			{% endautoescape %}
		</div>
	</div>
	<div class="col-sm-12 padding_all">
		<div class="blog_5">
	  			<!-- AddToAny BEGIN -->
					<div class="a2a_kit a2a_kit_size_32 a2a_default_style">
						<a class="a2a_dd" href="https://www.addtoany.com/share"></a>
						<a class="a2a_button_facebook"></a>
						<a class="a2a_button_twitter"></a>
						<a class="a2a_button_email"></a>
						<a class="a2a_button_whatsapp"></a>
						<a class="a2a_button_reddit"></a>
						<a class="a2a_button_telegram"></a>
						<a class="a2a_button_tumblr"></a>
						<a class="a2a_button_blogger"></a>
						<a class="a2a_button_facebook_messenger"></a>
						<a class="a2a_button_digg"></a>
						<a class="a2a_button_vk"></a>
						<a class="a2a_button_wordpress"></a>
					</div>
					<script>
					var a2a_config = a2a_config || {};
					a2a_config.locale = "pt-BR";
					</script>
					<script async src="https://static.addtoany.com/menu/page.js"></script>
					<!-- AddToAny END -->
			</div>
		</div>

	<div class="col-sm-12 padding_all">
		<div class="details_4">
			<h5>O que achou?</h5>
			<p>Deixe sua opinião nos comentários :-)</p>
				{% get_comment_list for post as comment_list %}
				{% for comment in comment_list %}
				<h5>
					{% if comment.url %}
					<a href="{{ comment.url }}" target="_blank">{{ comment.name }}</a>
					{% else %}
					{{ comment.name }}
					{% endif %}
				</h5>
				<p>{{ comment.submit_date }}</p>
				<p>{{ comment.comment }}</p>
				{% endfor %}
			</div>

			{% get_comment_form for post as comment_form %}
			<form action="{% comment_form_target %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="next" value="{{ post.get_absolute_url }}#comments" />
				<div class="details_6">
					<label for="id_name">Nome:</label>
					<input type="text" id="id_name" name="name" class="form-control" placeholder="" />
				</div>
				<div class="details_6">
					<label for="id_email">E-mail:</label>
					<input type="text" id="id_email" name="email" class="form-control" placeholder="" />
				</div>
				<div class="details_6">
					<label for="id_url">Website:</label>
					<input type="text" id="id_url" name="url" class="form-control" placeholder="" />
				</div>
				<div class="details_5">
					<label for="id_comment">Comentário:</label>
					<textarea class="form-control" placeholder="" id="id_comment" name="comment"></textarea>
				</div>
				<input id="id_honeypot" type="hidden" name="honeypot" />
				{{ comment_form.content_type }}
				{{ comment_form.object_pk }}
				{{ comment_form.timestamp }}
				{{ comment_form.security_hash }}

				<input type="submit" name="submit" value="Post">
				<input type="submit" name="preview" value="Preview">
			</form>

		</div>
	</div>
	{% endblock %}
	{% block js_script %}
<script type="text/javascript">
window.fbAsyncInit = function(){
FB.init({
    appId: '1353894315002911', status: true, cookie: true, xfbml: true });
};
(function(d, debug){var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
    if(d.getElementById(id)) {return;}
    js = d.createElement('script'); js.id = id;
    js.async = true;js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
    ref.parentNode.insertBefore(js, ref);}(document, /*debug*/ false));
function postToFeed(title, desc, url, image){
var obj = {method: 'feed',link: url, picture: image,name: title,description: desc};
function callback(response){}
FB.ui(obj, callback);
}

$('.btnShareFacebook').click(function(){
    elem = $(this);
    postToFeed(elem.data('title'), elem.data('desc'), elem.prop('href'), elem.data('image'));
    return false;
});
</script>
{% endblock %}